### PR TITLE
Moved PDFs to Document folder

### PR DESCRIPTION
**Pull request by CTZxVULKAN**
The following pdfs have been moved under the Documents folder

- SPARK-MAX-Java-API-Offline.pdf => Documents/SPARK-MAX-Java-API-Offline.pdf
- Tome of Secrets.pdf => Documents/Tome of Secrets.pdf 
-  limelight stuff.pdf => Documents/limelight stuff.pdf

### CODE REVIEW

**Comment by BobSaidHi** [comment]
Hey, thanks.  Would you mind also updating index.md with the new links (I believe that's the only page were they are referenced)?  I guess I should have mentioned that in #82.

**Comment by CTZxVULKAN** [comment]
Links corrosponding to the files that were changed right ?

**Comment by BobSaidHi** [comment]
Yep.

**Comment by CTZxVULKAN** [comment]
I could change the links in my repo but when you merge the links will lead to my fork of the project.
I suggest that you merge this first and close this PR.

**Comment by BobSaidHi** [comment]
Ok, thanks.

**Comment by CTZxVULKAN** [comment]
I am working on another project rn. I will do this as soon as the other PR is done .
:)

**Pull request merged**
